name: TranslateAPI
main: lion.translateapi.Main
version: "0.1.0b"
api: ["1.0.0"]

author: _Lion
description: Api for translate string

commands:
  translate:
    description: translate string
    usage: "/translate <langTo> <text>"
  getLangs:
    description: get the langs short names
    usage: "/getLangs"
permissions: